version: "3.8"
services:
  backend:
    build: ./
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
  frontend:
    build: ../generic-forum-fe/
    ports:
      - "5173:5173"
    volumes:
      - ../generic-forum-fe/generic-forum/:/app
